version: '3'
services:
  zk:
    image: zookeeper:3.4.14
    container_name: zk
    ports:
    - 2181:2181
  namesrv:
    image: rocketmqinc/rocketmq:4.3.2
    container_name: namesrv
    command: sh mqnamesrv
    ports:
    - 9876:9876
  broker:
    image: rocketmqinc/rocketmq:4.3.2
    container_name: broker
    links:
    - namesrv
    depends_on:
    - namesrv
    command: sh mqbroker -n namesrv:9876 -c /conf/broker.conf
    volumes:
    - ./broker.conf:/conf/broker.conf
    ports:
    - 10909:10909
    - 10911:10911
  console:
    image: styletang/rocketmq-console-ng
    container_name: console
    links:
    - namesrv
    depends_on:
    - namesrv
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false -Duser.timezone=Asia/Shanghai
    ports:
    - 8080:8080
  activemq:
    image: rmohr/activemq:5.14.5
    container_name: activemq
    ports:
    - 61616:61616
    - 8161:8161
